// <auto-generated />
using System;
using AttachmentService.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AttachmentService.Migrations
{
    [DbContext(typeof(AttachmentContext))]
    [Migration("20260830131107_SeedRealisticDemoData")]
    partial class SeedRealisticDemoData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AttachmentService.Models.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Checksum")
                        .HasColumnType("longtext");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Attachments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000001"),
                            ContentType = "application/pdf",
                            CreatedAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Signed-off requirements specification.",
                            FileName = "requirements-spec.pdf",
                            FileSize = 358400L,
                            OriginalFileName = "Requirements Specification.pdf",
                            ProjectId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            Status = 2,
                            StoragePath = "projects/a1b2c3d4-e5f6-7890-abcd-ef1234567890/d0000001-0000-0000-0000-000000000001.pdf",
                            UploadedByUserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000002"),
                            ContentType = "image/png",
                            CreatedAt = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "UI mockup for the sprint board & burndown task.",
                            FileName = "sprint-board-mockup.png",
                            FileSize = 128000L,
                            OriginalFileName = "Sprint Board Mockup.png",
                            ProjectId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            Status = 2,
                            StoragePath = "projects/a1b2c3d4-e5f6-7890-abcd-ef1234567890/tasks/80000001-0000-0000-0000-000000000003/d0000001-0000-0000-0000-000000000002.png",
                            TaskId = new Guid("80000001-0000-0000-0000-000000000003"),
                            UploadedByUserId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("d0000003-0000-0000-0000-000000000001"),
                            ContentType = "application/pdf",
                            CreatedAt = new DateTime(2025, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Final checkout flow diagram delivered with the redesign.",
                            FileName = "checkout-flow-diagram.pdf",
                            FileSize = 204800L,
                            OriginalFileName = "Checkout Flow Diagram.pdf",
                            ProjectId = new Guid("a3000000-0000-0000-0000-000000000003"),
                            Status = 2,
                            StoragePath = "projects/a3000000-0000-0000-0000-000000000003/tasks/80000003-0000-0000-0000-000000000001/d0000003-0000-0000-0000-000000000001.pdf",
                            TaskId = new Guid("80000003-0000-0000-0000-000000000001"),
                            UploadedByUserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("d0000002-0000-0000-0000-000000000001"),
                            ContentType = "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                            CreatedAt = new DateTime(2026, 6, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Compliance sign-off report for the GDPR/PSD2 milestone.",
                            FileName = "banking-compliance-report.docx",
                            FileSize = 92160L,
                            OriginalFileName = "Banking Compliance Report.docx",
                            ProjectId = new Guid("a2000000-0000-0000-0000-000000000002"),
                            Status = 2,
                            StoragePath = "projects/a2000000-0000-0000-0000-000000000002/d0000002-0000-0000-0000-000000000001.docx",
                            UploadedByUserId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
