// <auto-generated />
using System;
using AttachmentService.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AttachmentService.Migrations
{
    [DbContext(typeof(AttachmentContext))]
    partial class AttachmentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AttachmentService.Models.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Checksum")
                        .HasColumnType("longtext");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Attachments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            ContentType = "application/pdf",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Seed data - attached directly to the project.",
                            FileName = "project-charter.pdf",
                            FileSize = 204800L,
                            OriginalFileName = "Project Charter.pdf",
                            ProjectId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Status = 2,
                            StoragePath = "projects/11111111-1111-1111-1111-111111111111/33333333-3333-3333-3333-333333333333.pdf",
                            UploadedByUserId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            ContentType = "image/png",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Seed data - attached to a task, should also show up when listing the parent project's attachments.",
                            FileName = "bug-screenshot.png",
                            FileSize = 102400L,
                            OriginalFileName = "Screenshot 2026-01-01.png",
                            ProjectId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Status = 2,
                            StoragePath = "projects/11111111-1111-1111-1111-111111111111/tasks/22222222-2222-2222-2222-222222222222/44444444-4444-4444-4444-444444444444.png",
                            TaskId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UploadedByUserId = new Guid("55555555-5555-5555-5555-555555555555")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
