// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationService.Context;

#nullable disable

namespace NotificationService.Migrations
{
    [DbContext(typeof(NotificationServiceContext))]
    [Migration("20260830131218_SeedRealisticDemoData")]
    partial class SeedRealisticDemoData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NotificationService.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f0000001-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "You were assigned to task 'Build sprint board & burndown view' on Project Management System.",
                            IsRead = false,
                            Type = "TaskAssigned",
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("f0000001-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sprint 'Sprint 3 - Reporting & Notifications' started on Project Management System.",
                            IsRead = true,
                            Type = "SprintStarted",
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("f0000001-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Invoice for Mobile Banking App is overdue - the last payment attempt failed.",
                            IsRead = false,
                            Type = "InvoiceOverdue",
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("f0000001-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Your project 'E-Commerce Platform Redesign' has been marked as completed.",
                            IsRead = true,
                            Type = "ProjectCompleted",
                            UserId = new Guid("44444444-4444-4444-4444-444444444444")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
