// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkPackageService.Context;

#nullable disable

namespace WorkPackageService.Migrations
{
    [DbContext(typeof(WorkPackageServiceContext))]
    [Migration("20260830131150_SeedRealisticDemoData")]
    partial class SeedRealisticDemoData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WorkPackageService.Models.Backlog", b =>
                {
                    b.Property<Guid>("BacklogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("BacklogId");

                    b.ToTable("Backlogs");

                    b.HasData(
                        new
                        {
                            BacklogId = new Guid("60000001-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Unscheduled work for the Project Management System project.",
                            Name = "Project Management System Backlog",
                            ProjectId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            BacklogId = new Guid("60000003-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Unscheduled work for the E-Commerce Platform Redesign project.",
                            Name = "E-Commerce Platform Redesign Backlog",
                            ProjectId = new Guid("a3000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("WorkPackageService.Models.Comment", b =>
                {
                    b.Property<Guid>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CommentId");

                    b.HasIndex("TaskId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("WorkPackageService.Models.Dependency", b =>
                {
                    b.Property<Guid>("DependencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BlockerTaskId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("char(36)");

                    b.HasKey("DependencyId");

                    b.HasIndex("BlockerTaskId");

                    b.HasIndex("TaskId");

                    b.ToTable("Dependencies");
                });

            modelBuilder.Entity("WorkPackageService.Models.Task", b =>
                {
                    b.Property<Guid>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ApproverId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ParentTaskId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<Guid?>("SprintId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("WorkPackageId")
                        .HasColumnType("char(36)");

                    b.HasKey("TaskId");

                    b.HasIndex("ParentTaskId");

                    b.HasIndex("WorkPackageId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            TaskId = new Guid("80000001-0000-0000-0000-000000000001"),
                            ApproverId = new Guid("22222222-2222-2222-2222-222222222222"),
                            AssigneeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "REST endpoints for creating, updating and deleting projects and milestones.",
                            DueDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 2,
                            SprintId = new Guid("50000001-0000-0000-0000-000000000001"),
                            Status = 3,
                            Title = "Implement Project & Milestone CRUD API",
                            UpdatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkPackageId = new Guid("70000001-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            TaskId = new Guid("80000001-0000-0000-0000-000000000002"),
                            ApproverId = new Guid("22222222-2222-2222-2222-222222222222"),
                            AssigneeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Frontend screens for inviting, activating and removing project members.",
                            DueDate = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 1,
                            SprintId = new Guid("50000001-0000-0000-0000-000000000002"),
                            Status = 3,
                            Title = "Build project member management UI",
                            UpdatedAt = new DateTime(2026, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkPackageId = new Guid("70000001-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            TaskId = new Guid("80000001-0000-0000-0000-000000000003"),
                            ApproverId = new Guid("22222222-2222-2222-2222-222222222222"),
                            AssigneeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Drag-and-drop sprint board plus a burndown chart per sprint.",
                            DueDate = new DateTime(2026, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 2,
                            SprintId = new Guid("50000001-0000-0000-0000-000000000003"),
                            Status = 1,
                            Title = "Build sprint board & burndown view",
                            UpdatedAt = new DateTime(2026, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkPackageId = new Guid("70000001-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            TaskId = new Guid("80000003-0000-0000-0000-000000000001"),
                            ApproverId = new Guid("11111111-1111-1111-1111-111111111111"),
                            AssigneeId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Single-page checkout with saved payment methods, replacing the old 3-step flow.",
                            DueDate = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 2,
                            SprintId = new Guid("50000003-0000-0000-0000-000000000001"),
                            Status = 3,
                            Title = "Rebuild one-page checkout flow",
                            UpdatedAt = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkPackageId = new Guid("70000003-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("WorkPackageService.Models.WorkPackage", b =>
                {
                    b.Property<Guid>("WorkPackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("WorkPackageId");

                    b.ToTable("WorkPackages");

                    b.HasData(
                        new
                        {
                            WorkPackageId = new Guid("70000001-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2026, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Project, milestone and member management CRUD endpoints and UI.",
                            Name = "Core CRUD Module",
                            ProjectId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            Status = 3,
                            UpdatedAt = new DateTime(2026, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            WorkPackageId = new Guid("70000001-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2026, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sprint board, task tracking and reporting/notification features.",
                            Name = "Sprint & Reporting Module",
                            ProjectId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            WorkPackageId = new Guid("70000003-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "One-page checkout flow with saved payment methods.",
                            Name = "Checkout Redesign",
                            ProjectId = new Guid("a3000000-0000-0000-0000-000000000003"),
                            Status = 3,
                            UpdatedAt = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("WorkPackageService.Models.Comment", b =>
                {
                    b.HasOne("WorkPackageService.Models.Task", null)
                        .WithMany("Comments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkPackageService.Models.Dependency", b =>
                {
                    b.HasOne("WorkPackageService.Models.Task", null)
                        .WithMany()
                        .HasForeignKey("BlockerTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkPackageService.Models.Task", null)
                        .WithMany("Dependencies")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkPackageService.Models.Task", b =>
                {
                    b.HasOne("WorkPackageService.Models.Task", null)
                        .WithMany("SubTasks")
                        .HasForeignKey("ParentTaskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WorkPackageService.Models.WorkPackage", null)
                        .WithMany("Tasks")
                        .HasForeignKey("WorkPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkPackageService.Models.Task", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Dependencies");

                    b.Navigation("SubTasks");
                });

            modelBuilder.Entity("WorkPackageService.Models.WorkPackage", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
