// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentService.Context;

#nullable disable

namespace PaymentService.Migrations
{
    [DbContext(typeof(PaymentContext))]
    [Migration("20260830131135_SeedRealisticDemoData")]
    partial class SeedRealisticDemoData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PaymentService.Models.Invoice", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("IssuedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("InvoiceId");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            InvoiceId = new Guid("e1000001-0000-0000-0000-000000000001"),
                            IssueDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssuedByUserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ProjectId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            Status = 0,
                            TotalAmount = 4200.00m
                        },
                        new
                        {
                            InvoiceId = new Guid("e1000002-0000-0000-0000-000000000001"),
                            IssueDate = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssuedByUserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ProjectId = new Guid("a2000000-0000-0000-0000-000000000002"),
                            Status = 0,
                            TotalAmount = 9000.00m
                        },
                        new
                        {
                            InvoiceId = new Guid("e1000003-0000-0000-0000-000000000001"),
                            IssueDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssuedByUserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ProjectId = new Guid("a3000000-0000-0000-0000-000000000003"),
                            Status = 1,
                            TotalAmount = 15000.00m
                        });
                });

            modelBuilder.Entity("PaymentService.Models.InvoiceItem", b =>
                {
                    b.Property<Guid>("InvoiceItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("InvoiceItemId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceItems");

                    b.HasData(
                        new
                        {
                            InvoiceItemId = new Guid("e2000001-0000-0000-0000-000000000001"),
                            Description = "Core CRUD Module - development (sprints 1-2)",
                            InvoiceId = new Guid("e1000001-0000-0000-0000-000000000001"),
                            Quantity = 70,
                            TotalAmount = 4200.00m,
                            UnitPrice = 60.00m
                        },
                        new
                        {
                            InvoiceItemId = new Guid("e2000002-0000-0000-0000-000000000001"),
                            Description = "Security audit and remediation",
                            InvoiceId = new Guid("e1000002-0000-0000-0000-000000000001"),
                            Quantity = 100,
                            TotalAmount = 9000.00m,
                            UnitPrice = 90.00m
                        },
                        new
                        {
                            InvoiceItemId = new Guid("e2000003-0000-0000-0000-000000000001"),
                            Description = "Checkout Redesign - development and QA",
                            InvoiceId = new Guid("e1000003-0000-0000-0000-000000000001"),
                            Quantity = 120,
                            TotalAmount = 9000.00m,
                            UnitPrice = 75.00m
                        },
                        new
                        {
                            InvoiceItemId = new Guid("e2000003-0000-0000-0000-000000000002"),
                            Description = "Project management and delivery",
                            InvoiceId = new Guid("e1000003-0000-0000-0000-000000000001"),
                            Quantity = 60,
                            TotalAmount = 6000.00m,
                            UnitPrice = 100.00m
                        });
                });

            modelBuilder.Entity("PaymentService.Models.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PaidByUserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentId = new Guid("e3000002-0000-0000-0000-000000000001"),
                            Amount = 9000.00m,
                            Date = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceId = new Guid("e1000002-0000-0000-0000-000000000001"),
                            PaidByUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Status = 2
                        },
                        new
                        {
                            PaymentId = new Guid("e3000003-0000-0000-0000-000000000001"),
                            Amount = 15000.00m,
                            Date = new DateTime(2025, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceId = new Guid("e1000003-0000-0000-0000-000000000001"),
                            PaidByUserId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Status = 1
                        });
                });

            modelBuilder.Entity("PaymentService.Models.InvoiceItem", b =>
                {
                    b.HasOne("PaymentService.Models.Invoice", "Invoice")
                        .WithMany("Items")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("PaymentService.Models.Payment", b =>
                {
                    b.HasOne("PaymentService.Models.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("PaymentService.Models.Invoice", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
