// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimelogService.Context;

#nullable disable

namespace TimelogService.Migrations
{
    [DbContext(typeof(TimelogContext))]
    [Migration("20260830131051_SeedRealisticDemoData")]
    partial class SeedRealisticDemoData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TimelogService.Models.Timelog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("HoursSpent")
                        .HasColumnType("double");

                    b.Property<Guid>("LoggedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Timelogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("90000001-0000-0000-0000-000000000001"),
                            Date = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoursSpent = 6.0,
                            LoggedByUserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ProjectId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            TaskId = new Guid("80000001-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("90000001-0000-0000-0000-000000000002"),
                            Date = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoursSpent = 5.5,
                            LoggedByUserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ProjectId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            TaskId = new Guid("80000001-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("90000001-0000-0000-0000-000000000003"),
                            Date = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoursSpent = 4.0,
                            LoggedByUserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ProjectId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            TaskId = new Guid("80000001-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("90000003-0000-0000-0000-000000000001"),
                            Date = new DateTime(2025, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoursSpent = 7.0,
                            LoggedByUserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ProjectId = new Guid("a3000000-0000-0000-0000-000000000003"),
                            TaskId = new Guid("80000003-0000-0000-0000-000000000001")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
