// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimelogService.Context;

#nullable disable

namespace TimelogService.Migrations
{
    [DbContext(typeof(TimelogContext))]
    partial class TimelogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TimelogService.Models.Timelog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("HoursSpent")
                        .HasColumnType("double");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WorkPackageId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Timelogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a411c13-a195-48f7-8dbd-67596c3974c0"),
                            Date = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoursSpent = 4.5,
                            ProjectId = new Guid("044f3de0-a9dd-4c2e-b745-89976a1b2a36"),
                            WorkPackageId = new Guid("21ad52f8-0281-4241-98b0-481566d25e4f")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
