// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectService.Context;

#nullable disable

namespace ProjectService.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20260829222550_SeedDemoData")]
    partial class SeedDemoData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProjectService.Models.Milestone", b =>
                {
                    b.Property<Guid>("MilestoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("ExpectedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.HasKey("MilestoneId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Milestones");

                    b.HasData(
                        new
                        {
                            MilestoneId = new Guid("c0000001-0000-0000-0000-000000000001"),
                            Description = "All functional and non-functional requirements documented and signed off by stakeholders.",
                            ExpectedDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Requirements gathering complete",
                            ProjectId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            MilestoneId = new Guid("c0000001-0000-0000-0000-000000000002"),
                            Description = "UI/UX mockups, database schema and API contracts finalized.",
                            ExpectedDate = new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Design phase done",
                            ProjectId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            MilestoneId = new Guid("c0000001-0000-0000-0000-000000000003"),
                            Description = "Project, milestone and member management modules deployed to staging.",
                            ExpectedDate = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Core modules delivered",
                            ProjectId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            MilestoneId = new Guid("c0000001-0000-0000-0000-000000000004"),
                            Description = "Full regression suite passing; user acceptance testing approved.",
                            ExpectedDate = new DateTime(2026, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Testing complete",
                            ProjectId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            MilestoneId = new Guid("c0000001-0000-0000-0000-000000000005"),
                            Description = "System live in production with monitoring and backups enabled.",
                            ExpectedDate = new DateTime(2026, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Production release",
                            ProjectId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            MilestoneId = new Guid("c0000002-0000-0000-0000-000000000001"),
                            Description = "Penetration testing completed with no critical vulnerabilities outstanding.",
                            ExpectedDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Security audit passed",
                            ProjectId = new Guid("a2000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            MilestoneId = new Guid("c0000002-0000-0000-0000-000000000002"),
                            Description = "Card and instant-transfer rails integrated with the core banking API.",
                            ExpectedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Payments integration live",
                            ProjectId = new Guid("a2000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            MilestoneId = new Guid("c0000002-0000-0000-0000-000000000003"),
                            Description = "Feature-complete build distributed to 200 internal testers.",
                            ExpectedDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Beta release",
                            ProjectId = new Guid("a2000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            MilestoneId = new Guid("c0000002-0000-0000-0000-000000000004"),
                            Description = "Regulatory review completed for GDPR and PSD2 requirements.",
                            ExpectedDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Compliance sign-off",
                            ProjectId = new Guid("a2000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            MilestoneId = new Guid("c0000003-0000-0000-0000-000000000001"),
                            Description = "Stakeholder interviews and competitive analysis delivered.",
                            ExpectedDate = new DateTime(2024, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Discovery workshop complete",
                            ProjectId = new Guid("a3000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            MilestoneId = new Guid("c0000003-0000-0000-0000-000000000002"),
                            Description = "Component library and brand guidelines ratified by the design board.",
                            ExpectedDate = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "New design system approved",
                            ProjectId = new Guid("a3000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            MilestoneId = new Guid("c0000003-0000-0000-0000-000000000003"),
                            Description = "One-page checkout with saved payment methods shipped.",
                            ExpectedDate = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Checkout flow rebuilt",
                            ProjectId = new Guid("a3000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            MilestoneId = new Guid("c0000003-0000-0000-0000-000000000004"),
                            Description = "Largest Contentful Paint under 2s on 3G; Lighthouse score above 90.",
                            ExpectedDate = new DateTime(2025, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Performance targets met",
                            ProjectId = new Guid("a3000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            MilestoneId = new Guid("c0000003-0000-0000-0000-000000000005"),
                            Description = "Redesigned storefront rolled out to 100% of traffic.",
                            ExpectedDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Launch",
                            ProjectId = new Guid("a3000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            MilestoneId = new Guid("c0000004-0000-0000-0000-000000000001"),
                            Description = "Build-vs-buy decision made and single sign-on provider selected.",
                            ExpectedDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Vendor selection complete",
                            ProjectId = new Guid("a4000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            MilestoneId = new Guid("c0000004-0000-0000-0000-000000000002"),
                            Description = "Employee directory, leave requests and org chart prioritized for phase 1.",
                            ExpectedDate = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "MVP scope locked",
                            ProjectId = new Guid("a4000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            MilestoneId = new Guid("c0000004-0000-0000-0000-000000000003"),
                            Description = "Core self-service features available to all staff.",
                            ExpectedDate = new DateTime(2027, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Phase 1 delivered",
                            ProjectId = new Guid("a4000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            MilestoneId = new Guid("c0000004-0000-0000-0000-000000000004"),
                            Description = "Performance reviews and reporting dashboards added.",
                            ExpectedDate = new DateTime(2027, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Phase 2 delivered",
                            ProjectId = new Guid("a4000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            MilestoneId = new Guid("c0000004-0000-0000-0000-000000000005"),
                            Description = "Legacy HR system decommissioned.",
                            ExpectedDate = new DateTime(2027, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Full rollout",
                            ProjectId = new Guid("a4000000-0000-0000-0000-000000000004")
                        });
                });

            modelBuilder.Entity("ProjectService.Models.Project", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Budget")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ProjectId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ProjectId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            Budget = 10000,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Project Management System",
                            Status = 1
                        },
                        new
                        {
                            ProjectId = new Guid("a2000000-0000-0000-0000-000000000002"),
                            Budget = 45000,
                            CreatedAt = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mobile Banking App",
                            Status = 2
                        },
                        new
                        {
                            ProjectId = new Guid("a3000000-0000-0000-0000-000000000003"),
                            Budget = 78000,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2026, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "E-Commerce Platform Redesign",
                            Status = 3
                        },
                        new
                        {
                            ProjectId = new Guid("a4000000-0000-0000-0000-000000000004"),
                            Budget = 22000,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2027, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Internal HR Portal",
                            Status = 0
                        });
                });

            modelBuilder.Entity("ProjectService.Models.ProjectMember", b =>
                {
                    b.Property<Guid>("ProjectMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("ProjectMemberId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectMembers");

                    b.HasData(
                        new
                        {
                            ProjectMemberId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            JoinedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            Status = true,
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            ProjectMemberId = new Guid("b0000001-0000-0000-0000-000000000002"),
                            JoinedAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            Status = true,
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            ProjectMemberId = new Guid("b0000002-0000-0000-0000-000000000001"),
                            JoinedAt = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectId = new Guid("a2000000-0000-0000-0000-000000000002"),
                            Status = true,
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ProjectMemberId = new Guid("b0000002-0000-0000-0000-000000000002"),
                            JoinedAt = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectId = new Guid("a2000000-0000-0000-0000-000000000002"),
                            Status = true,
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            ProjectMemberId = new Guid("b0000002-0000-0000-0000-000000000003"),
                            JoinedAt = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectId = new Guid("a2000000-0000-0000-0000-000000000002"),
                            Status = false,
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            ProjectMemberId = new Guid("b0000003-0000-0000-0000-000000000001"),
                            JoinedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectId = new Guid("a3000000-0000-0000-0000-000000000003"),
                            Status = true,
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            ProjectMemberId = new Guid("b0000003-0000-0000-0000-000000000002"),
                            JoinedAt = new DateTime(2024, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectId = new Guid("a3000000-0000-0000-0000-000000000003"),
                            Status = true,
                            UserId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            ProjectMemberId = new Guid("b0000004-0000-0000-0000-000000000001"),
                            JoinedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectId = new Guid("a4000000-0000-0000-0000-000000000004"),
                            Status = true,
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ProjectMemberId = new Guid("b0000004-0000-0000-0000-000000000002"),
                            JoinedAt = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectId = new Guid("a4000000-0000-0000-0000-000000000004"),
                            Status = true,
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            ProjectMemberId = new Guid("b0000004-0000-0000-0000-000000000003"),
                            JoinedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectId = new Guid("a4000000-0000-0000-0000-000000000004"),
                            Status = true,
                            UserId = new Guid("44444444-4444-4444-4444-444444444444")
                        });
                });

            modelBuilder.Entity("ProjectService.Models.Requirement", b =>
                {
                    b.Property<Guid>("RequirementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.HasKey("RequirementId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Requirements");

                    b.HasData(
                        new
                        {
                            RequirementId = new Guid("d0000001-0000-0000-0000-000000000001"),
                            Description = "The system must support at least 100 concurrent authenticated users without response-time degradation.",
                            ProjectId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            RequirementId = new Guid("d0000001-0000-0000-0000-000000000002"),
                            Description = "Every API endpoint must respond within 200 ms for the 95th percentile under normal load.",
                            ProjectId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            RequirementId = new Guid("d0000001-0000-0000-0000-000000000003"),
                            Description = "Deleting a project must cascade to all of its milestones, requirements and members.",
                            ProjectId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            RequirementId = new Guid("d0000001-0000-0000-0000-000000000004"),
                            Description = "Only users with the Admin or ProjectManager role may create or edit projects.",
                            ProjectId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            RequirementId = new Guid("d0000001-0000-0000-0000-000000000005"),
                            Description = "All timestamps must be stored and returned in UTC.",
                            ProjectId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            RequirementId = new Guid("d0000002-0000-0000-0000-000000000001"),
                            Description = "All data in transit must be encrypted using TLS 1.2 or higher.",
                            ProjectId = new Guid("a2000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RequirementId = new Guid("d0000002-0000-0000-0000-000000000002"),
                            Description = "User sessions must expire after 5 minutes of inactivity.",
                            ProjectId = new Guid("a2000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RequirementId = new Guid("d0000002-0000-0000-0000-000000000003"),
                            Description = "The app must remain usable offline for read-only account balance viewing.",
                            ProjectId = new Guid("a2000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RequirementId = new Guid("d0000002-0000-0000-0000-000000000004"),
                            Description = "Every financial transaction must be recorded in an immutable audit log.",
                            ProjectId = new Guid("a2000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RequirementId = new Guid("d0000002-0000-0000-0000-000000000005"),
                            Description = "Biometric authentication must be supported on devices that provide it.",
                            ProjectId = new Guid("a2000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RequirementId = new Guid("d0000003-0000-0000-0000-000000000001"),
                            Description = "Product search must return results within 500 ms for a catalogue of 50,000 items.",
                            ProjectId = new Guid("a3000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RequirementId = new Guid("d0000003-0000-0000-0000-000000000002"),
                            Description = "The storefront must be fully usable on screens as small as 320 px wide.",
                            ProjectId = new Guid("a3000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RequirementId = new Guid("d0000003-0000-0000-0000-000000000003"),
                            Description = "Checkout must be completable in no more than three steps.",
                            ProjectId = new Guid("a3000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RequirementId = new Guid("d0000003-0000-0000-0000-000000000004"),
                            Description = "The site must meet WCAG 2.1 AA accessibility conformance.",
                            ProjectId = new Guid("a3000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RequirementId = new Guid("d0000004-0000-0000-0000-000000000001"),
                            Description = "Employees must be able to submit and track leave requests without contacting HR directly.",
                            ProjectId = new Guid("a4000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RequirementId = new Guid("d0000004-0000-0000-0000-000000000002"),
                            Description = "The portal must integrate with the existing corporate single sign-on provider.",
                            ProjectId = new Guid("a4000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RequirementId = new Guid("d0000004-0000-0000-0000-000000000003"),
                            Description = "A manager must be notified within one hour of a direct report submitting a request.",
                            ProjectId = new Guid("a4000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RequirementId = new Guid("d0000004-0000-0000-0000-000000000004"),
                            Description = "Personally identifiable information must be accessible only to HR staff and the employee it belongs to.",
                            ProjectId = new Guid("a4000000-0000-0000-0000-000000000004")
                        });
                });

            modelBuilder.Entity("ProjectService.Models.Milestone", b =>
                {
                    b.HasOne("ProjectService.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectService.Models.ProjectMember", b =>
                {
                    b.HasOne("ProjectService.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectService.Models.Requirement", b =>
                {
                    b.HasOne("ProjectService.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
