// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectService.Context;

#nullable disable

namespace ProjectService.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20260406202421_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProjectService.Models.Milestone", b =>
                {
                    b.Property<Guid>("MilestoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ExpectedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.HasKey("MilestoneId");

                    b.ToTable("Milestones");

                    b.HasData(
                        new
                        {
                            MilestoneId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            ExpectedDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        });
                });

            modelBuilder.Entity("ProjectService.Models.Project", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Budget")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ProjectId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ProjectId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            Budget = 10000,
                            Name = "Project Management System",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("ProjectService.Models.ProjectMember", b =>
                {
                    b.Property<Guid>("ProjectMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("ProjectMemberId");

                    b.ToTable("ProjectMembers");

                    b.HasData(
                        new
                        {
                            ProjectMemberId = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            JoinedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            Status = true,
                            UserId = new Guid("e5f6a7b8-c9d0-1234-efab-345678901234")
                        });
                });

            modelBuilder.Entity("ProjectService.Models.Requirements", b =>
                {
                    b.Property<Guid>("RequirementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.HasKey("RequirementId");

                    b.ToTable("Requirements");

                    b.HasData(
                        new
                        {
                            RequirementId = new Guid("d4e5f6a7-b8c9-0123-defa-234567890123"),
                            Description = "Initial project requirements",
                            ProjectId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
