// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserService.Context;

#nullable disable

namespace UserService.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20260818180312_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("UserService.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ContactInfo = "+381600000001",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@example.com",
                            IsActive = true,
                            Name = "Admin Administrator",
                            PasswordHash = "/2wtJodhL70wFJHy8xv+RAlJ35PWHK82KHONu0E2lpI=",
                            Role = 0,
                            Salt = "Umf/S8pkKxiY2lRQjFSSpw==",
                            Username = "admin"
                        },
                        new
                        {
                            UserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ContactInfo = "+381600000002",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "pm@example.com",
                            IsActive = true,
                            Name = "Petar Projektni",
                            PasswordHash = "/2wtJodhL70wFJHy8xv+RAlJ35PWHK82KHONu0E2lpI=",
                            Role = 1,
                            Salt = "Umf/S8pkKxiY2lRQjFSSpw==",
                            Username = "pm"
                        },
                        new
                        {
                            UserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ContactInfo = "+381600000003",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "member@example.com",
                            IsActive = true,
                            Name = "Marko Član",
                            PasswordHash = "/2wtJodhL70wFJHy8xv+RAlJ35PWHK82KHONu0E2lpI=",
                            Role = 2,
                            Salt = "Umf/S8pkKxiY2lRQjFSSpw==",
                            Username = "member"
                        },
                        new
                        {
                            UserId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ContactInfo = "+381600000004",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "client@example.com",
                            IsActive = true,
                            Name = "Klijent Test",
                            PasswordHash = "/2wtJodhL70wFJHy8xv+RAlJ35PWHK82KHONu0E2lpI=",
                            Role = 3,
                            Salt = "Umf/S8pkKxiY2lRQjFSSpw==",
                            Username = "client"
                        });
                });

            modelBuilder.Entity("UserService.Models.UserActivityLog", b =>
                {
                    b.Property<Guid>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Details")
                        .HasColumnType("longtext");

                    b.Property<Guid>("PerformedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("LogId");

                    b.ToTable("UserActivityLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
